Models/Edad.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finder.Models
{
     public class Edad
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdEdad { get; set; }
        [Required]
        public string Nombre { get; set; }
        
        
    }
}

Models/ErrorViewModel.cs
using System;

namespace Finder.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Especie.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finder.Models
{
    public class Especie
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdEspecie { get; set; }
        [Required]
        public string Nombre { get; set; }
        
        
    }
}

Models/Estado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finder.Models
{
    public class Estado
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdEstado { get; set; }
        [Required]
        public string Nombre { get; set; }
        
        
    }
}

Models/Porte.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finder.Models
{
    public class Porte
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdPorte { get; set; }
        [Required]
        public string Nombre { get; set; }
        
        
    }
}

Models/Publicacion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finder.Models
{
    public class Publicacion
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        public Usuario IdUsuario { get; set; }
        [Required]
        public Estado IdEstado { get; set; }
        [Required]
        public Raza IdRaza { get; set; }
        [Required]
        public Especie IdEspecie { get; set; }
        [Required]
        public Edad  IdEdad { get; set; }
        [Required]
        public Porte IdPorte { get; set; }
        [Required]
        public Zona  IdZona { get; set; }
        public List<Publicacion> Publicaciones { get; set; }    
    }
}

Models/Raza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finder.Models
{
     public class Raza
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdRaza { get; set; }
        [Required]
        public string Nombre { get; set; }
        
        
    }
}

Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace Finder.Models
{
    public class Usuario : IdentityUser
    {
        public string Nombre { get; set; }

        public string Apellido { get; set; }
    }
}

Models/Zona.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finder.Models
{
    public class Zona
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdZona { get; set; }
        [Required]
        public string Nombre { get; set; }
        
        
    }
    
}

Controllers/EnAdopcionController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Finder.Models;
using Finder.Data;

namespace Finder.Controllers
{
    public class EnAdopcionController : PublicacionesController
    {

        public EnAdopcionController(ApplicationDbContext context) : base(context)
        {
        }
        // public IActionResult Publicaciones()
        // {
        //     return View();
        // }
        // public IActionResult Detalles()
        // {
        //     return View();
        // }
        // public IActionResult Crear()
        // {
        //     return View();
        // }
        // public IActionResult Editar()
        // {
        //     return View();
        // }
        // public IActionResult Eliminar()
        // {
        //     return View();
        // }
    }
}

Controllers/EncontradosController.cs
using Finder.Data;
using Microsoft.AspNetCore.Mvc;

namespace Finder.Controllers
{
    public class EncontradosController : PublicacionesController
    {
        public EncontradosController(ApplicationDbContext context) : base(context)
        {
        }

        // public IActionResult Publicaciones()
        // {
        //     return View();
        // }
        // public IActionResult Detalles()
        // {
        //     return View();
        // }
        // public IActionResult Crear()
        // {
        //     return View();
        // }
        // public IActionResult Editar()
        // {
        //     return View();
        // }
        // public IActionResult Eliminar()
        // {
        //     return View();
        // }
    }
}

Controllers/EspeciesController.cs
using System.Collections.Generic;
using System.Linq;
using Finder.Data;
using Finder.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Finder.Controllers
{
    public class EspeciesController : Controller
    { 
        private readonly ApplicationDbContext Context;
        public EspeciesController(ApplicationDbContext context)
        {
            Context = context;
        }
        
        public List<Especie> GetAll()
        {
            return Context.Especies.ToList();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Finder.Models;

namespace Finder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PerdidosController.cs
using Finder.Data;
using Microsoft.AspNetCore.Mvc;

namespace Finder.Controllers
{
    public class PerdidosController : PublicacionesController
    {
        public PerdidosController(ApplicationDbContext context) : base(context)
        {
        }

        // public IActionResult Publicaciones()
        // {
        //     return View();
        // }
        // public IActionResult Detalles()
        // {
        //     return View();
        // }
        // public IActionResult Crear()
        // {
        //     return View();
        // }
        // public IActionResult Editar()
        // {
        //     return View();
        // }
        // public IActionResult Eliminar()
        // {
        //     return View();
        // }
    }
}

Controllers/PublicacionesController.cs
using System.Linq;
using Finder.Data;
using Finder.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Finder.Controllers
{
    public class PublicacionesController : Controller
    {
        private readonly ApplicationDbContext Context;
        public PublicacionesController(ApplicationDbContext context)
        {
            Context = context;
        }
        public IActionResult Publicaciones()
        {
            return View();
        }
        public IActionResult Detalles()
        {
            return View();
        }
        [Authorize]
        public IActionResult Crear()
        {
            ViewBag.EspecieId = new SelectList(Context.Especies, "IdEspecie", "Nombre");
            return View(new Publicacion());
        }
        [Authorize]
        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult GetEliminar()
        {
            return View();
        }

        public IActionResult Buscar()
        {
            return View();
        }
        
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Publicaciones/Buscar.cshtml
<h1>Realiza tu busqueda aqui</h1>


<form action="">
    <div>
    <p>Buscar una mascota:
    <select name="Estado" required>
      <option value="">Elige una opción</option>
      <option value="1">Perdida</option>
      <option value="2">Encontrada</option>
      <option value="3">En Adopcion</option>
    </select>
    </p>
    </div>

    <div>
    <p>Especie:   
    <select name="Especie" required>
      <option value="">Elige una opción</option>
      <option value="1">Perro</option>
      <option value="2">Gato</option>
      <option value="3">Ave</option>
      <option value="4">Roedor</option>
      <option value="5">Reptil</option>
      <option value="6">Otro</option>
    </select>
    </p>
    </div>

    <div>
    <p>Raza:  
    <select name="Raza" >
      <option value="">Elige una opción</option>
      <option value="1"></option>
      <option value="2"></option>
      <option value="3"></option>
      <option value="4"></option>
      <option value="5"></option>
      <option value="6">Otro</option>
    </select>
    </p>
    </div>
    <div>
    <p>Porte:
    <select name="Porte" required>
      <option value="">Elige una opción</option>
      <option value="1">Pequeño</option>
      <option value="2">Mediano</option>
      <option value="3">Grande</option>
    </select>
    </p>
    </div>
    <div>
    <p>Edad:  
    <select name="Edad" required>
      <option value="">Elige una opción</option>
      <option value="1">Cachorro</option>
      <option value="2">Adulto</option>
      <option value="3">Adulto Mayor</option>
      <option value="4">No sabe</option>
    </select>
    </p>
    </div>

    <div>
    <p>Zona:
    <select name="Zona" id="Zona" required>  
      <option value="">Elige una opción</option>
      <option value="1">Centro</option>
      <option value="2">Norte</option>
      <option value="3">Sur</option>
      <option value="4">Este</option>
      <option value="5">Oeste</option>
    </select>
    </p>
    </div>

    <div>
      <label for="Barrio">Barrio</label>
        <input type="text" name="Barrio" id="Barrio" required>
    </div>

    <input type="submit" value="Buscar">                
    <input type="reset" value="Restaurar">
</form>

Views/Publicaciones/Crear.cshtml
@model Finder.Models.Publicacion

<h1>Publica aqui a tu mascota</h1>

<form action="">
  <div>
    <p>Publicar un mascota:
      <select name="Estado" required>

        <option value="">Elige una opción</option>
        <option value="1">Perdida</option>
        <option value="2">Encontrada</option>
        <option value="3">En Adopcion</option>
      </select>
    </p>
  </div>
  <div>
    <p>Especie:
    </p>
    <select asp-for="IdEspecie" class="form-control" asp-items="ViewBag.EspecieId"></select>
    @* <select name="Especie" required>
      <option value="">Elige una opción</option>
      <option value="1">Perro</option>
      <option value="2">Gato</option>
      <option value="3">Ave</option>
      <option value="4">Roedor</option>
      <option value="5">Reptil</option>
      <option value="6">Otro</option>
      </select> *@

  </div>
  <div>
    <p>Raza:
      <select name="Raza">

        <option value="">Elige una opción</option>
        <option value="1"></option>
        <option value="2"></option>
        <option value="3"></option>
        <option value="4"></option>
        <option value="5"></option>
        <option value="6">Otro</option>
      </select>
    </p>
  </div>
  <div>
    <p>Porte:
      <select name="Porte" required>

        <option value="">Elige una opción</option>
        <option value="1">Pequeño</option>
        <option value="2">Mediano</option>
        <option value="3">Grande</option>
      </select>
    </p>
  </div>
  <div>
    <p>Edad:
      <select name="Edad" required>

        <option value="">Elige una opción</option>
        <option value="1">Cachorro</option>
        <option value="2">Adulto</option>
        <option value="3">Adulto Mayor</option>
        <option value="4">No sabe</option>
      </select>
    </p>
  </div>
  <div>
    <p>Zona:
      <select name="Zona" required>

        <option value="">Elige una opción</option>
        <option value="1">Centro</option>
        <option value="2">Norte</option>
        <option value="3">Sur</option>
        <option value="4">Este</option>
        <option value="5">Oeste</option>
      </select>
    </p>
  </div>
  <div>
    <label for="Barrio">Barrio:</label>
    <input type="text" name="Barrio" id="Barrio" required>
  </div>
  <div>
    <label for="Fecha">Fecha:</label>
    <input type="date" name="Fecha" id="Fecha" required>
  </div>
  <div>
    <label for="Foto">Subir una Foto:</label>
    <input type="file" name="Foto" id="Foto">
  </div>
  <div>
    <label for="Descripcion">Descripcion:</label>
    <input type="text" name="Descripcion" id="Descripcion" placeholder="Breve informacion que consideres importante"
      maxlength="100">
  </div>

  <input type="submit" value="Guardar">
  <input type="reset" value="Restaurar">
</form>

Views/Publicaciones/Detalles.cshtml
<h1>Detalles</h1>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Editar">Editar</a>
            <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Borrar">Borrar</a>
    </div>
    </nav>

Views/Publicaciones/Publicaciones.cshtml
<h1>Publicaciones</h1>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Crear">Publicar</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Buscar">Buscar</a>
    </div>
    </nav>

    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Finder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Finder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Publicaciones">Mascotas Perdidas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Publicaciones">Mascotas Encontradas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Publicaciones">Mascotas en Adopcion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Crear">Publicar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publicaciones" asp-action="Buscar">Buscar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Finder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>